### ISSUE TITLE
Running build or test gives 'project-root' function error

### ISSUE THREAD

**Issue by kirill-gerasimenko** [sebasmonia/sharper#14]
Hi,

I've added sharper and if I invoke build or test - I get the following error:
`sharper--project-root: Symbol’s function definition is void: project-root`.

I'm using the latest emacs 27 on linux. 

Great project!

**Comment by omajid** [comment]
Same error, but on emacs 26.3 here.

`project-root` was added recently: http://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/progmodes/project.el?id=5044c19001fe608f2eac621add2e05cbca6c804b

It's [not present in the latest 27.1 RC tag](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/project.el?h=emacs-27.1-rc1&id=27877e7bcfa37b2c97a3dde170f870d4729ff807). That still uses the older `project-roots` function.

**Comment by sebasmonia** [comment]
I guess the best solution is to add a function `shaper--project-root` and `defalias` it when `project-root` is not defined.
The other alternative is to replace all calls to project-root with a new function internal to the package.

Open to suggestions :)
Will look at this later today, but PRs are welcomed too.

Thank you for your support!

**Comment by sebasmonia** [comment]
Added a fix in a157858, let me know after you verify and we can close this one.

Thank you!

**Comment by sebasmonia** [comment]
Loaded the package in Emacs 26.3 and it worked OK. Will close this now but would love verification from the reporters!

**Comment by kirill-gerasimenko** [comment]
@sebasmonia seems to work, thanks for the fix!
