### ISSUE TITLE
Extra empty buffer is created when running dotnet core project

### ISSUE THREAD

**Issue by kirill-gerasimenko** [sebasmonia/sharper#17]
Hi, 

First of all - thanks agian for the great project!

I'm using Sharper for the aspnet core project on linux. When I run `run` command - 2 buffers open, one with name `dotnet run` and without anything happening in it, and the other one `dotnet run ....<all the parameters>` which has process running. The first one seems unnecessary? 

Best regards,
Kirill

**Comment by sebasmonia** [comment]
Thanks for reporting this issue! I will try to reproduce. 
Might have been caused by a recent change to the logic to pop buffers in a few functions.

**Comment by sebasmonia** [comment]
@kirill-gerasimenko which version of Emacs are you using?

**Comment by kirill-gerasimenko** [comment]
@sebasmonia using 27.1 on linux. I can still reproduce it - when I run the project it opens empty buffer with `* dotnet run - <project name> *` and a separate buffer with the full `dotnet run params`. But this might be me advicing shell running func. Will try without advises and get back to you.

**Comment by kirill-gerasimenko** [comment]
Yeah, closing the issue, it was my advice function messing up things.

**Comment by sebasmonia** [comment]
Great, thank you for checking!
