### ISSUE TITLE
Question: dotnet watch - is it supported? 

### ISSUE THREAD

**Issue by kirill-gerasimenko-da** [sebasmonia/sharper#27]
Hi, thanks for the great package!!

I'm trying to figure out how to use `dotnet watch` with Sharper, but without luck. Is this supported somehow? That would be great if it was possible (say as an additional flag in Run menu). 

Kirill

**Comment by sebasmonia** [comment]
Hi, thank you! Happy it is useful for you :) 

I wasn't aware about `dotnet watch` until just now. Based on the examples in the documentation, it seems like something worth adding to both `run` and `test`. After selecting all other options, we could have `r` for `run` and `w` for `watch run`. In that latter case the process would keep running until you manually stop it, and `dotnet` would take care of re-starting when there are changes to the source. 
Same for `t`/`wt` for test/watch test, although this one might be a bit more involved as right now it runs in compilation-mode, which isn't designed around keeping the process open. Test would run in compilation-mode, and watch test would run in a regular async-shell.

What do you think of this proposal? I'm open to suggestions based on your workflow.

**Comment by kirill-gerasimenko-da** [comment]
@sebasmonia thanks for you reply!

The way you put this - sounds great to me! I like the idea of adding `w` to Run and Test commands and async-shell for tests - looks to me as a reasonable solution.

**Comment by sebasmonia** [comment]
Merged the changes.

**Comment by kirill-gerasimenko-da** [comment]
@sebasmonia sorry for the late reply. This works for me perfectly! Thanks for adding this functionality - I really appreciate it!

**Comment by kirill-gerasimenko-da** [comment]
> watch test cannot target a solution, it has to be a project. I tried using different invocations but nothing worked. In most of the projects I know there is a single test project, but we have a few at work with tests spread over a number of projects. How limiting to you think this is?

For me having single test project is usual, so I don't have any other thoughts :man_shrugging:

**Comment by sebasmonia** [comment]
Great! Let me know if you find issues. 👍
