### ISSUE TITLE
Accessing Nuget Package search, etc. from main transient?

### ISSUE THREAD

**Issue by McPhale** [sebasmonia/sharper#32]
I can't seem to find a way to get to the nuget search/installation features from the main transient; am I just missing something?  

Thanks for this great project!

**Comment by sebasmonia** [comment]
Hi!!!
I'm glad you like the project, hope it is useful for you :pray: 

You get to the Nuget stuff using "mp" in the main transient. It stands for "manage packages". 

Note that packages are per-project, so what's gonna happen is that Sharper will try to find the _nearest project file_ from whatever path you have invoked the transient from.
Another way to put it, from whichever `cs`/`fs` file (or dired directory) you invoke the transient from, will affect the project which packages are listed.

When looking at the packages listing, hit RET (enter) to see the possible actions, like search NuGet, remove the package at point, etc.

If you are able to install things, feel free to close the issue, and if you run into problems, just let me know!

**Comment by McPhale** [comment]
Ah ok, I think I must have a conflicting key binding in my config then or something; hitting RET on the package listing page just drops the cursor down a line.  I'll go ahead and close the ticket, thanks for your help :)

**Comment by sebasmonia** [comment]
Just checked the code (it's been a while since I touched it ooops) and you can bind in the function `sharper-transient-project-packages` to some key in your evil-mode keymaps to trigger that menu.

**Comment by McPhale** [comment]
Great! Thank you!

**Comment by McPhale** [comment]
Leaving this here for anyone else that runs into this:

```elisp
  (evil-make-overriding-map sharper--nuget-results-mode-map)
  (evil-make-overriding-map sharper--project-packages-mode-map)
```
